version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Google.Apis.Drive.v3
    versions:
    - 1.49.0.2201
    - 1.49.0.2223
    - 1.50.0.2223
    - 1.50.0.2229
    - 1.50.0.2236
    - 1.50.0.2250
    - 1.51.0.2265
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
